from abc import ABC, abstractmethod
from typing import List
from app.db.models.event_model import Event
from uuid import UUID

class EventInterface(ABC):
    @abstractmethod
    async def get_all_events(self, skip:int, limit:int, filters:dict | None = None) -> List[Event] | None:...
    @abstractmethod
    async def get_event_by_id(self, event_id: UUID) -> Event | None:...
    @abstractmethod
    async def create_event(self, event: Event) -> Event:...
    @abstractmethod
    async def update_event(self, event_id:UUID, data:dict) -> Event:...
    @abstractmethod
    async def delete_event(self, event_id:UUID) -> bool:...
    @abstractmethod
    async def count_events(self) -> int:...
    @abstractmethod
    async def get_participant_count(self, event_id:UUID) -> int:...