from abc import ABC, abstractmethod
from typing import List
from app.db.models.organization_model import Organization
from uuid import UUID

class OrganizationInterface(ABC):
    @abstractmethod
    async def get_all_organizations(self, skip:int, limit:int, filters:dict | None = None)->List[Organization] | None:...
    @abstractmethod
    async def get_organization_by_id(self, organization_id:UUID)->Organization | None:...
    @abstractmethod
    async def create_organization(self, organization:Organization)->Organization:...
    @abstractmethod
    async def update_organization(self, organization_id:UUID, data:dict)->Organization:...
    @abstractmethod
    async def delete_organization(self, organization_id:UUID)->bool:...