apiVersion: apps/v1
kind: Deployment
metadata:
  # Utilise nameOverride si défini, sinon utilise le nom de la release Helm
  name: {{ .Values.nameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}

# Ce spec est à la racine (0 espace) : c'est celui du Deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      app: {{ .Values.nameOverride | default .Release.Name }}
  
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride | default .Release.Name }}
        version: {{ .Values.appVersion }}
        
    
   
    spec:
      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}-{{ .Release.Name }}
      {{- end }}
      
      containers:
        - name: {{ .Release.Name }}-container
          # Concaténation du repository et du tag de l'image
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              {{- toYaml .Values.securityContext.capabilities | nindent 14 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.servicePort }}
              protocol: TCP
          {{- if .Values.readinessProbe.enabled }}    
          readinessProbe:
              httpGet:
                # On utilise la variable du values.yaml, avec "/" par défaut si oubliée
                path: {{ .Values.readinessProbe.path | default "/" }}
                # Petite astuce K8s : tu peux utiliser le nom du port défini juste au-dessus !
                port: http 
              initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 30 }}
              periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            {{- end }}
        {{- with .Values.env }}
          env:
            
            {{- toYaml . | nindent 12 }}
        {{- end }}

        {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
        {{- end }}

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}
      
      {{- with .Values.volumes }}
      volumes:
            {{- toYaml . | nindent 8 }}
      {{- end }}