{{- if .Values.imagePullSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret.name }}-{{ .Release.Name }}
  # Il est préférable d'utiliser .Release.Namespace pour déployer là où le chart est installé
  namespace: {{ .Release.Namespace }} 
spec:
  refreshInterval: {{ .Values.imagePullSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.imagePullSecret.store.name }}
    kind: {{ .Values.imagePullSecret.store.kind }}
  target:
    name: {{ .Values.imagePullSecret.name }}-{{ .Release.Name }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        # L'astuce est ici : on utilise {{` ... `}} pour que Helm n'essaie pas d'évaluer le Go template d'External Secrets
        .dockerconfigjson: '{"auths":{"{{`{{ .docker_server }}`}}":{"username":"{{`{{ .docker_username }}`}}","password":"{{`{{ .docker_password }}`}}","auth":"{{`{{ printf "%s:%s" .docker_username .docker_password | b64enc }}`}}"}}}'
  data:
    - secretKey: docker_server
      remoteRef:
        key: {{ .Values.imagePullSecret.scalewaySecretId | quote }}
        property: docker-server
    - secretKey: docker_username
      remoteRef:
        key: {{ .Values.imagePullSecret.scalewaySecretId | quote }}
        property: docker-username
    - secretKey: docker_password
      remoteRef:
        key: {{ .Values.imagePullSecret.scalewaySecretId | quote }}
        property: docker-password
{{- end }}