"""ajout de l'adresse pour les orga

Revision ID: 136e6cf2ca10
Revises: 546e91935fc4
Create Date: 2026-04-08 16:33:24.934087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136e6cf2ca10'
down_revision: Union[str, Sequence[str], None] = '546e91935fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'addresses', ['address_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'address_id')
    # ### end Alembic commands ###
