"""ajout relation parent-enfant pour les users

Revision ID: 168aa2cc0f1e
Revises: 9b016c57e4ed
Create Date: 2026-04-21 15:10:49.705043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168aa2cc0f1e'
down_revision: Union[str, Sequence[str], None] = '9b016c57e4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_relationships',
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('minor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['minor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guardian_id', 'minor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardian_relationships')
    # ### end Alembic commands ###
