"""relation entre user et adresse

Revision ID: 222166e012d7
Revises: 8f9690f9c454
Create Date: 2026-03-23 15:22:05.200038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222166e012d7'
down_revision: Union[str, Sequence[str], None] = '8f9690f9c454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. ajouter colonnes nullable
    op.add_column('users', sa.Column('home_address_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('residential_address_id', sa.Integer(), nullable=True))

    # 2. créer une adresse par défaut (CORRIGÉ)
    op.execute("""
    INSERT INTO addresses (id, box_number, street, post_name, post_code, country)
    VALUES (1, '0', 'Adresse par défaut', 'Ville', '0000', 'Belgique')
    ON CONFLICT (id) DO NOTHING
    """)

    # 3. remplir users
    op.execute("""
    UPDATE users
    SET home_address_id = 1
    WHERE home_address_id IS NULL
    """)

    # 4. rendre NOT NULL
    op.alter_column('users', 'home_address_id', nullable=False)

    # 5. FK
    op.create_foreign_key(None, 'users', 'addresses', ['home_address_id'], ['id'])
    op.create_foreign_key(None, 'users', 'addresses', ['residential_address_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'residential_address_id')
    op.drop_column('users', 'home_address_id')
    # ### end Alembic commands ###
