"""update address model

Revision ID: 273884052001
Revises: f426ed3f9046
Create Date: 2026-04-08 12:02:23.763905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273884052001'
down_revision: Union[str, Sequence[str], None] = 'f426ed3f9046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add thoroughfare as nullable first to avoid NOT NULL violation on existing rows
    op.add_column('addresses', sa.Column('thoroughfare', sa.String(), nullable=True))
    op.execute("UPDATE addresses SET thoroughfare = 'unknown'")
    op.alter_column('addresses', 'thoroughfare', nullable=False)
    op.drop_column('addresses', 'street')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'thoroughfare')
    # ### end Alembic commands ###
