"""suppression en cascade pour les contacts

Revision ID: 2e3187ea1eba
Revises: a7781dec7ace
Create Date: 2026-03-16 16:37:21.121746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3187ea1eba'
down_revision: Union[str, Sequence[str], None] = 'a7781dec7ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
