"""liaison entre event et address

Revision ID: 4a0aa8d83698
Revises: d60d8008f57c
Create Date: 2026-04-09 15:31:56.764653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0aa8d83698'
down_revision: Union[str, Sequence[str], None] = 'd60d8008f57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'address_id')
    # ### end Alembic commands ###
