"""ajout d'un champ pour le nbre max de participants à un event

Revision ID: 502991c8af96
Revises: 4943465dbabf
Create Date: 2026-05-05 15:44:00.002145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502991c8af96'
down_revision: Union[str, Sequence[str], None] = '4943465dbabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Ajouter la colonne nullable temporairement
    op.add_column('events', sa.Column('max_participants', sa.Integer(), nullable=True))

    # 2. Remplir les données existantes
    op.execute("UPDATE events SET max_participants = 25")

    # 3. Rendre la colonne non nullable
    op.alter_column('events', 'max_participants', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'max_participants')
    # ### end Alembic commands ###
