"""changemant cardinalité du numéro de boite

Revision ID: 546e91935fc4
Revises: 273884052001
Create Date: 2026-04-08 15:44:22.127147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546e91935fc4'
down_revision: Union[str, Sequence[str], None] = '273884052001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'box_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'box_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
