"""Ajout du modèle d'organisation

Revision ID: 5a481730f0d6
Revises: 243324609935
Create Date: 2026-03-10 11:18:04.766407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a481730f0d6'
down_revision: Union[str, Sequence[str], None] = '243324609935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legal_form', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('REGION', 'UNIT', 'SECTION', 'PATROLS', 'SIXES', 'ASSOCIATION', 'FEDERAL_INSTANCE', 'COMMISSION', 'WORKING_GROUP', 'ER', 'EU', 'EFT', 'FCT', 'COM', 'PARTNER', 'SUPPLIER', 'AUTHORITY', 'INSTITUTION', name='organization_type_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations')
    # ### end Alembic commands ###
