"""ajout de la table contacts et correction des autres tables

Revision ID: a7781dec7ace
Revises: a1319e497325
Create Date: 2026-03-16 10:38:11.029783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7781dec7ace'
down_revision: Union[str, Sequence[str], None] = 'a1319e497325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('memberships', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('memberships', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.add_column('organizations', sa.Column('sgp_type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('org_type', sa.String(), nullable=True))
    op.execute("UPDATE organizations SET org_type = 'unknown' WHERE org_type IS NULL")
    op.alter_column('organizations', 'org_type', nullable=False)

    op.add_column('organizations', sa.Column('is_legal_entity', sa.Boolean(), nullable=True))
    op.execute("UPDATE organizations SET is_legal_entity = false WHERE is_legal_entity IS NULL")
    op.alter_column('organizations', 'is_legal_entity', nullable=False)
    op.add_column('organizations', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'contacts', ['contact_id'], ['id'])
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'zip')
    op.drop_column('organizations', 'type')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'street')
    op.drop_column('organizations', 'legal_form')
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('totem', sa.String(), nullable=True))
    op.add_column('users', sa.Column('quali', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_names', sa.JSON(), nullable=True))
    op.execute("UPDATE users SET first_names = '[]' WHERE first_names IS NULL")
    op.alter_column('users', 'first_names', nullable=False)

    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.execute("UPDATE users SET last_name = 'unknown' WHERE last_name IS NULL")
    op.alter_column('users', 'last_name', nullable=False)

    op.add_column('users', sa.Column('is_legal_guardian', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_legal_guardian = false WHERE is_legal_guardian IS NULL")
    op.alter_column('users', 'is_legal_guardian', nullable=False)
    op.add_column('users', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'contacts', ['contact_id'], ['id'])
    op.drop_column('users', 'birthDate')
    op.drop_column('users', 'firstNames')
    op.drop_column('users', 'zip')
    op.drop_column('users', 'city')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'street')
    op.drop_column('users', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstNames', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'contact_id')
    op.drop_column('users', 'is_legal_guardian')
    op.drop_column('users', 'quali')
    op.drop_column('users', 'totem')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_names')
    op.add_column('organizations', sa.Column('legal_form', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('type', postgresql.ENUM('REGION', 'UNIT', 'SECTION', 'PATROLS', 'SIXES', 'ASSOCIATION', 'FEDERAL_INSTANCE', 'COMMISSION', 'WORKING_GROUP', 'ER', 'EU', 'EFT', 'FCT', 'COM', 'PARTNER', 'SUPPLIER', 'AUTHORITY', 'INSTITUTION', name='organization_type_enum'), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'contact_id')
    op.drop_column('organizations', 'is_legal_entity')
    op.drop_column('organizations', 'sgp_type')
    op.drop_column('organizations', 'org_type')
    op.alter_column('memberships', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('memberships', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table('contacts')
    # ### end Alembic commands ###
