"""ajout relation entre adresse et org/users

Revision ID: ac0a740aee65
Revises: 136e6cf2ca10
Create Date: 2026-04-08 16:44:41.858489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0a740aee65'
down_revision: Union[str, Sequence[str], None] = '136e6cf2ca10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
