"""Renommage de la table contenant les utilisateurs

Revision ID: b212ab36ef74
Revises: cdc1a739d16d
Create Date: 2026-03-06 11:14:55.805096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b212ab36ef74'
down_revision: Union[str, Sequence[str], None] = 'cdc1a739d16d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstNames', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('persons_pkey')),
    sa.UniqueConstraint('email', name=op.f('persons_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
