"""ajout du role dans le mandat

Revision ID: b9f2bd80db78
Revises: a55fa1d4697f
Create Date: 2026-03-11 16:19:51.356836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9f2bd80db78'
down_revision: Union[str, Sequence[str], None] = 'a55fa1d4697f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('role', sa.String(), nullable=False))
    op.alter_column('memberships', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('memberships', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('memberships', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('memberships', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('memberships', 'role')
    # ### end Alembic commands ###
