"""changement relations contact

Revision ID: e218965777f2
Revises: fcc01ab0497d
Create Date: 2026-03-17 09:22:49.726700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e218965777f2'
down_revision: Union[str, Sequence[str], None] = 'fcc01ab0497d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contacts', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('organizations_contact_id_fkey'), 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'contact_id')
    op.drop_constraint(op.f('users_contact_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'contact_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_contact_id_fkey'), 'users', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.add_column('organizations', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('organizations_contact_id_fkey'), 'organizations', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'org_id')
    op.drop_column('contacts', 'user_id')
    # ### end Alembic commands ###
