"""suppression en cascade des sous-organisations

Revision ID: f6b9bf449c90
Revises: b8538d5df682
Create Date: 2026-03-17 14:32:18.623576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b9bf449c90'
down_revision: Union[str, Sequence[str], None] = 'b8538d5df682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_parent_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'organizations', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_parent_id_fkey'), 'organizations', 'organizations', ['parent_id'], ['id'])
    # ### end Alembic commands ###
