"""correction suppression en cascad

Revision ID: fcc01ab0497d
Revises: 2e3187ea1eba
Create Date: 2026-03-16 16:40:55.269114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc01ab0497d'
down_revision: Union[str, Sequence[str], None] = '2e3187ea1eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_contact_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_contact_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_contact_id_fkey'), 'users', 'contacts', ['contact_id'], ['id'])
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_contact_id_fkey'), 'organizations', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###
