from abc import ABC, abstractmethod
from typing import List
from app.db.models.user_model import User
from uuid import UUID

class UserInterface(ABC):
    @abstractmethod
    async def create_user(self, person: User) -> User: ...
    @abstractmethod
    async def get_users(self, skip:int, limit:int, filters:dict | None = None) -> List[User]: ...
    @abstractmethod
    async def get_user_by_id(self, user_id: UUID) -> User | None: ...
    @abstractmethod
    async def update_user(self, user_id:UUID, data:dict) -> User: ...
    @abstractmethod
    async def delete_user(self, user_id:UUID) -> bool: ...