apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      app: {{ .Values.nameOverride | default .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride | default .Release.Name }}
        version: {{ .Values.appVersion }}

    spec:
      
      {{- if .Values.rbac.enabled }}
      # Associer le Service Account au Deployment pour les permissions RBAC
      serviceAccountName: {{ .Release.Name }}-sa
      automountServiceAccountToken: false
      {{- end }}
      # IMPORTANT POUR KSV-0118
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}-{{ .Release.Name }}
      {{- end }}

      containers:
        - name: {{ .Release.Name }}-container

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

            capabilities:
              drop:
                - ALL

            seccompProfile:
              type: RuntimeDefault

          ports:
            - name: http

              # IMPORTANT:
              # évite les ports <1024
              containerPort: {{ .Values.servicePort }}

              protocol: TCP

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/" }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          {{- end }}

          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}

            requests:
              cpu: {{ .Values.resources.requests.cpu | default "250m" }}
              memory: {{ .Values.resources.requests.memory | default "256Mi" }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}