{{- if .Values.imagePullSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret.name }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

spec:
  refreshInterval: {{ .Values.imagePullSecret.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.imagePullSecret.store.name }}
    kind: {{ .Values.imagePullSecret.store.kind }}

  target:
    name: {{ .Values.imagePullSecret.name }}-{{ .Release.Name }}
    creationPolicy: Owner

    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"{{`{{ .docker_server }}`}}":{"username":"{{`{{ .docker_username }}`}}","password":"{{`{{ .docker_password }}`}}","auth":"{{`{{ printf "%s:%s" .docker_username .docker_password | b64enc }}`}}"}}}'

  data:
    - secretKey: docker_server
      remoteRef:
        key: {{ .Values.imagePullSecret.scalewaySecretId | quote }}
        property: docker-server

    - secretKey: docker_username
      remoteRef:
        key: {{ .Values.imagePullSecret.scalewaySecretId | quote }}
        property: docker-username

    - secretKey: docker_password
      remoteRef:
        key: {{ .Values.imagePullSecret.scalewaySecretId | quote }}
        property: docker-password
{{- end }}

---

{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}

  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: {{ .Values.externalSecret.storeKind }}

  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: Owner

  data:
    {{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}