{{- range .Values.serviceEntries }}
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.nameOverride | default $.Release.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  location: {{ .location }}
  resolution: {{ .resolution }}
  {{- with .hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}