name: Pull, Push and Keyless Sign Indiana Backend (GitOps Flow)

on:
  push:
    branches:
      - main
    paths:
      - 'helm_chart/values.yaml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: [arc-runner-set]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Tag from values.yaml
        id: extract_tag
        run: |
          EXTRACTED_TAG=$(grep 'tag:' helm_chart/values.yaml | head -n1 | awk '{print $2}' | tr -d '"')
          if [ -z "$EXTRACTED_TAG" ]; then
            echo "Erreur : Impossible de trouver le tag dans helm_chart/values.yaml"
            exit 1
          fi
          echo "TAG_NAME=$EXTRACTED_TAG" >> $GITHUB_ENV
          echo "Tag extrait : $EXTRACTED_TAG"

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes

      - name: Build and Push image to Harbor
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/indiana-backend:${{ env.TAG_NAME }}
          cache-from: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/indiana-backend:cache
          cache-to: type=registry,ref=${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/indiana-backend:cache,mode=max

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image (keyless)
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          cosign sign --yes \
            ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT }}/indiana-backend@${DIGEST}